mod 'boxen', '3.6.1', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.1.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'propety_list_key', '0.2.1', :github_tarball => 'glarizza/puppet-property_list_key'